language: php
php:
  - 5.6
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env
  - php artisan key:generate
  - php artisan config:clear
script: phpunit
